DROP DATABASE IF EXISTS tracker_db;

CREATE DATABASE tracker_db;

USE tracker_db;

-- TABLE CREATION FOR ENTIRE DEPARTMENT --
CREATE TABLE departments (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);
-- TABLE CREATION FOR ROLES --
CREATE TABLE roles (
    id INT NOT NULL AUTO_INCREMENT,

)





SOURCE seeds.sql;